### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by phated**
@sttk please review these changes against your implementation.  I separated the new functionality from the test re-write so you can compare independently.

I also moved some of the utility methods around.

### CODE REVIEW

**Comment by phated** [comment]
We are so close!  I just want to make sure you are fine with the new defaulting behavior.

**Comment by phated** [comment]
I removed the Windows specific tests because we already test those cases on Windows just without the explicit description.

**Comment by sttk** [comment]
Great! I reviewed the codes and it's good. But there is only one point about test. 

The removed test cases are needed to test the code part [L79-L81](https://github.com/js-cli/fined/blob/ec18a2c7dba65a921575261479d4884f8d3bd800/index.js#L79-L81). The cause of NGs is that `path.resolve(winDrive)` is different from `process.cwd()` on mocha. This can be resolved by `if (isWindows) { process.chdir(process.cwd()); }` before testing.

**Comment by sttk** [comment]
@phated I merged your commits except avoiding Windows-specific tests and added workaround for the test cases to the `initial_code_commit` branch in this repository. So you can merge this code from the [js-cli/fined's PR #1](https://github.com/js-cli/fined/pull/1).

**Pull request merged**
